name: 'CI'

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
      - feature/*

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Node.js Setup
        uses: ./.github/actions/node-setup

      - name: Restore puppeteer cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - run: npm rebuild full-icu
    
      - name: Run Jest Tests
        run: npm run test-jest -- --ci

  playwright-component-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Node.js Setup
        uses: ./.github/actions/node-setup
        
      - name: Restore Playwright Browser Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers

      - name: Install Specific Playwright Browsers (Chromium and Firefox)
        run: npx playwright install chromium firefox

      - name: Run Playwright Component Tests
        run: CI=true npm run test-ct

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Node.js Setup
        uses: ./.github/actions/node-setup

      - name: Restore puppeteer cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: "run linter"
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm run lint
      - run: npm run bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
