name: 'CI'

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Restore puppeteer cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - run: npm ci
      - run: npm rebuild full-icu
      - run: npm run test --ci --runInBand

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Restore puppeteer cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - run: npm ci
      - name: "run linter"
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: npm run lint
      - run: npm run bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
