name: 'CI'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            **/node_modules
          key: ${{ matrix.node-version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ matrix.node-version }}-

      - run: yarn --frozen-lockfile
      - run: npm rebuild full-icu
      - run: yarn test --ci

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Restore cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            **/node_modules
          key: 14.x-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            14.x-

      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
          CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
