name: Update documentation to github pages

on:
  workflow_dispatch:

jobs:
  update-documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout exam-engine
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - name: Generate Offline Exams
        run: |
          npm install
          echo -n SC N MexDocumentation | xargs -d ' ' -P0 -I {} npm run ee create-offline packages/exams/{}/{}.xml  --outdir exams

      - name: Publish to GitHub Pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages
          git checkout gh-pages
          git status
          rm -rf MexDocumentation && cp -r packages/exams/MexDocumentation/2022-01-27_fi    MexDocumentation
          rm -rf SC/fi-FI         && cp -r packages/exams/SC/1970-01-01_SC_fi SC/fi-FI
          rm -rf SC/sv-FI         && cp -r packages/exams/SC/1970-01-01_SC_sv SC/sv-FI
          rm -rf SC/fi-FI-hi      && cp -r packages/exams/SC/1970-01-01_SC_fi_hi SC/fi-FI-hi
          rm -rf N/sv-FI          && cp -r packages/exams/N/2022-03-23_N_sv  N/sv-FI
          rm -rf N/fi-FI          && cp -r packages/exams/N/2022-03-23_N_fi  N/fi-FI
          rm -rf N/fi-FI-vi       && cp -r packages/exams/N/2022-03-23_N_fi_vi  N/fi-FI-vi
          git add MexDocumentation SC N
          git commit --allow-empty -m 'Update MexDocumentation, SC, and N sample exam'
          git push origin gh-pages
